sudo: false
language: ruby
rvm:
  - 2.5.1

addons:
  postgresql: "9.6"

before_install: gem install bundler -v 1.16.1

before_script:
  - cp spec/database.yml.travis spec/database.yml
  - bundle exec rake db:setup
